/*Copyright (C) 2014 Justin Green
  SHA512 sum of resume: ee1dcaa00b931696d73f0d978e39ac2c8302de27a5034b7035bd9111d1f48ddf9fae46842baa3af2a56f17f8043cdd5760ced014c223a13fab1ad29cbfb3748c
  How to use this checksum: open up directory with my resume and type "sha512sum resume.docx" into the bash prompt.
  Then compare the two checksums.

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.*/



#include <libdis.h>

#pragma once

enum var_type
{
	REG,
	GLOBAL,
	LOCAL,
	PARAM,
	CONST,
	DEREF
};

struct var //Later recycled as a search parameter struct for search_vars
{
	char* name;
	char* c_type;
	enum var_type type;
	union
	{
		unsigned int addr;
		int disp;
	} loc; //Location in memory of variable or value of constant
	struct var* next; //Also used as a return field in search_vars
};
typedef struct var var;

extern int name_ind; //Furthest "digit" of name modified
extern char last_name [20]; //Last name generated by gen_var_name
extern char c_types [4][10]; //String representations of data types in a normal C program, e.g. char or int

var* var_list;
var* global_list;
var* callee_param; //Linked list of parameters passed to current function
var* caller_param; //Dynamically allocated array filled with copies of the variables being passed to a function called within this function
int num_caller_params;
size_t caller_params_size;

char* gen_var_name (void); //Generates a unique variable name
var* init_var (var* to_init, x86_op_t operand); //Translates an operand into a C style variable
var* add_var (x86_op_t operand); //Add variable to linked list if not a dupe
void search_vars (var* to_check, var* key);
void cleanup_var (var* to_cleanup);
void clean_var_list (var* to_cleanup);
